sonar.projectKey=example-sonarqube
sonar.projectName=Example SonarQube
sonar.sourceEncoding=UTF-8
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.qualitygate.wait=true

# Exemplos de ajustes uteis para aula:
# sonar.exclusions=src/main/java/**/legacy/**
# sonar.coverage.exclusions=src/main/java/**/App.java
# sonar.test.inclusions=src/test/java/**/*Test.java
